/*
 * Copyright 2014 by Erik Hofman.
 * Copyright 2014 by Adalin B.V.
 * All Rights Reserved.
 *
 * This is UNPUBLISHED PROPRIETARY SOURCE CODE of Adalin B.V.;
 * the contents of this file may not be disclosed to third parties, copied or
 * duplicated in any form, in whole or in part, without the prior written
 * permission of Adalin B.V.
 */

#ifndef AAX_MIDI_H
#define AAX_MIDI_H 1

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(TARGET_OS_MAC) && TARGET_OS_MAC
# pragma export on
#endif

#include <aax/aax.h>

enum aaxMIDIStatus
{
   AAX_MIDI_NOTE_OFF = 0x80,
   AAX_MIDI_NOTE_ON = 0x90,
   AAX_MIDI_POLYPHONIC_AFTERTOUCH = 0xA0,
   AAX_MIDI_CONTROL_CHANGE = 0xB0,
   AAX_MIDI_PROGRAM_CHANGE = 0xC0,
   AAX_MIDI_CHANNEL_AFTERTOUCH = 0xD0,
   AAX_MIDI_PITCH_BEND = 0xE0,

   /* system messages */
   AAX_MIDI_SYSTEM_EXCLUSIVE = 0xF0,
   AAX_MIDI_TIME_CODE_QUARTER_FRAME,
   AAX_MIDI_SONG_POSITION_POINTER,
   AAX_MIDI_SONG_SELECT,
   AAX_MIDI_UNDEFINED_1,
   AAX_MIDI_UNDEFINED_2,
   AAX_MIDI_TUNE_REQUEST,
   AAX_MIDI_END_OF_EXCLUSIVE,
   AAX_MIDI_TIMING_CLOCK,
   AAX_MIDI_UNDEFINED_3,
   AAX_MIDI_START,
   AAX_MIDI_CONDTINUE,
   AAX_MIDI_STOP,
   AAX_MIDI_UNDEFINED_4,
   AAX_MIDI_ACTIVE_SENSING,
   AAX_MIDI_SYSTEM_RESET
};

enum aaxMIDIController
{
   AAX_MIDI_MODULATION = 1,
   AAX_MIDI_BREATH_CONTROLLER,
   AAX_MIDI_CONTROLLER_UNDEFINED_1,
   AAX_MIDI_FOOT_CONTROLLER,
   AAX_MIDI_PORTAMENTO_TIME,
   AAX_MIDI_DATA_ENTRY,
   AAX_MIDI_MAIN_VOLUME,
   AAX_MIDI_BALANCE,
   AAX_MIDI_CONTROLLER_UNDEFINED_2,
   AAX_MIDI_PAN,
   AAX_MIDI_EXPRESSION_CONTROLLER,

   AAX_MIDI_GENERAL_PURPOSE_14 = 0x10,
   AAX_MIDI_CONTROLLER_LSB = 0x20,
   AAX_MIDI_DAMPER_PEDAL = 0x40
   AAX_MIDI_PORTAMENTO,
   AAX_MIDI_SOSTENUTO,
   AAX_MIDI_SOFT_PEDAL,
   AAX_MIDI_CONTROLLER_UNDEFINED_3,
   AAX_MIDI_HOLD2,
   AAX_MIDI_CONTROLLER_UNDEFINED_4,
   AAX_MIDI_GENERAL_PURPOSE_58,
   AAX_MIDI_CONTROLLER_UNDEFINED_5,
   AAX_MIDI_EXTERNAL_EFFECT_DEPTH,
   AAX_MIDI_TREMOLO_DEPTH,
   AAX_MIDI_CHORUS_DEPTH,
   AAX_MIDI_CELESTE_DEPTH,	// detune
   AAX_MIDI_PHASER_DEPTH,
   AAX_MIDI_DATA_INCREMENT,
   AAX_MIDI_DATA_DECREMENT,
   AAX_MIDI_NONREGISTERED_PARAMETER_NO_LSB,
   AAX_MIDI_NONREGISTERED_PARAMETER_NO_MSB,
   AAX_MIDI_REGISTERED_PARAMETER_NO_LSB,
   AAX_MIDI_REGISTERED_PARAMETER_NO_MSB,
   AAX_MIDI_CONTROLLER_UNDEFINED_6,
   AAX_MIDI_MODE_MESSAGE
}

#if defined(TARGET_OS_MAC) && TARGET_OS_MAC
# pragma export off
#endif

#if defined(__cplusplus)
}  /* extern "C" */
#endif

#endif

