
# Component support
#SET(CPACK_COMPONENTS_ALL Applications Libraries Headers)
SET(CPACK_COMPONENTS_ALL Applications)

# Display name
SET(CPACK_COMPONENT_APPLICATIONS_HIDDEN ON)
SET(CPACK_COMPONENT_APPLICATIONS_DISPLAY_NAME "Command line utilities")
SET(CPACK_COMPONENT_DESKTOP_DISPLAY_NAME "Graphical Utilities")
SET(CPACK_COMPONENT_HEADERS_DISPLAY_NAME "C/C++ Development Files")

# Descriptions
SET(CPACK_COMPONENT_APPLICATIONS_DESCRIPTION
   "Support applictaions to test the capabilities of the software")
SET(CPACK_COMPONENT_LIBRARIES_DESCRIPTION
   "Dynamically shared components of the software")
SET(CPACK_COMPONENT_HEADERS_DESCRIPTION
   "Development header files and library components for use with the software")

# Dependecies
#SET(CPACK_COMPONENT_HEADERS_DEPENDS Libraries)
#SET(CPACK_COMPONENT_APPLICATIONS_DEPENDS Libraries)

# Component grouping
IF(WIN32)
  # NSIS
  SET(CPACK_COMPONENT_APPLICATIONS_GROUP "Runtime")
  SET(CPACK_COMPONENT_LIBRARIES_GROUP "Runtime")
  SET(CPACK_COMPONENT_HEADERS_GROUP "Development")
  SET(CPACK_COMPONENT_DESKTOP_GROUP "Desktop")

  # Note Windows DLL are specified by RUNTIME
  SET(CPACK_COMPONENT_GROUP_RUNTIME_DESCRIPTION
     "Command line utilities")
  SET(CPACK_COMPONENT_GROUP_DEVELOPMENT_DESCRIPTION
     "C/C++ Development headers and libraries")
  SET(CPACK_COMPONENT_GROUP_DESKTOP_DESCRIPTION
     "Graphical Utilities")

  SET(CPACK_ALL_INSTALL_TYPES Runtime Desktop Developer)
  SET(CPACK_COMPONENT_LIBRARIES_INSTALL_TYPES Runtime Developer)
  SET(CPACK_COMPONENT_HEADERS_INSTALL_TYPES Developer)
  SET(CPACK_COMPONENT_APPLICATIONS_INSTALL_TYPES Runtime Desktop)
  
ELSE(WIN32)
  SET(CPACK_COMPONENT_APPLICATIONS_GROUP "bin")
  SET(CPACK_COMPONENT_LIBRARIES_GROUP "bin")
  SET(CPACK_COMPONENT_HEADERS_GROUP "dev")
  SET(CPACK_COMPONENT_DESKTOP_GROUP "gui")
# SET(CPACK_DESKTOP_USE_DISPLAY_NAME_IN_FILENAME ON)

  SET(CPACK_COMPONENT_GROUP_BIN_DESCRIPTION
     "Command line utilities")
  SET(CPACK_COMPONENT_GROUP_DEV_DESCRIPTION
     "C/C++ Development headers and libraries")
  SET(CPACK_COMPONENT_GROUP_DESKTOP_DESCRIPTION
     "Graphical Utilities")

  SET(CPACK_ALL_INSTALL_TYPES bin dev gui)
  SET(CPACK_COMPONENT_LIBRARIES_INSTALL_TYPES bin dev)
  SET(CPACK_COMPONENT_HEADERS_INSTALL_TYPES dev)
  SET(CPACK_COMPONENT_APPLICATIONS_INSTALL_TYPES bin gui)
ENDIF(WIN32)

