#!/bin/sh -e
# Source debconf library.
. /usr/share/debconf/confmodule

if [ x$SUDO_USER != "x" ]; then
  INSTALLER=$SUDO_USER;
elif [ x$USER != "x" ]; then
  INSTALLER=$USER;
else
  INSTALLER=root;
fi

if [ x$INSTALLER = "x" ]; then
  CONFIGFILE="$HOME/.aaxconfig.xml"
  INSTALLER=`stat -c %U $HOME`
  GROUP=`stat -c %G $HOME`
else
  INSTALLER_HOME=`grep $INSTALLER /etc/passwd | cut -d ":" -f6`
  CONFIGFILE="$INSTALLER_HOME/.aaxconfig.xml"
  GROUP=`stat -c %G $INSTALLER_HOME`
fi

if [ x"$INSTALLER" = xroot ]; then
  if [ ! -d /etc/aax ] ;then
    mkdir /etc/aax;
  fi
  CONFIGFILE="/etc/aax/config.xml"
fi

db_reset libaax2/copyright_accept
db_reset libaax2/copyright

if [ ! -f "$CONFIGFILE" ]; then

  db_get libaax2/product_key
  KEY="$RET"

  echo "<?xml version="1.0"?>\n\n<Configuration>\n<product-key>$KEY</product-key>\n <output>\n  <frequency-hz>48000</frequency-hz>\n  <interval-hz>46</interval-hz>\n  <update-hz>20</update-hz>\n  <setup>stereo</setup>\n </output>\n</Configuration>" > $CONFIGFILE

  chmod 600 $CONFIGFILE
  chown $INSTALLER:$GROUP $CONFIGFILE
fi
db_reset libaax2/product_key

ldconfig
