#!/bin/sh -e

USER=$SUDO_USER
if [ x$USER = "x" ]; then
  CONFIGFILE="$HOME/.aaxconfig.xml"
  USER=`stat -c %U $HOME`
  GROUP=`stat -c %G $HOME`
else
  USER_HOME=`grep $USER /etc/passwd | cut -d ":" -f6`
  CONFIGFILE="$USER_HOME/.aaxconfig.xml"
  GROUP=`stat -c %G $USER_HOME`
fi

if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
  # Source debconf library.
  . /usr/share/debconf/confmodule
  # Remove my changes to the db.
  db_purge

  # remove stale configuration files
  if [ $USER = "root" ]; then
    if [ -d /etc/aax ] ;then
      rm -f /etc/aax/config.xml > /dev/null;
      rmdir /etc/aax > /dev/null;
    fi
  fi
  rm -f $CONFIGFILE;
fi

if [ "$1" = "remove" -o "$1" = "purge" ]; then
  ldconfig
fi
