#!/bin/sh -e

if [ x$SUDO_USER != "x" ]; then
  INSTALLER=$SUDO_USER;
elif [ x$USER != "x" ]; then
  INSTALLER=$USER;
else
  INSTALLER=root;
fi

if [ x$INSTALLER = "x" ]; then
  CONFIGFILE="$HOME/.aaxconfig.xml"
  INSTALLER=`stat -c %U $HOME`
# GROUP=`stat -c %G $HOME`
else
  INSTALLER_HOME=`grep $INSTALLER /etc/passwd | cut -d ":" -f6`
  CONFIGFILE="$INSTALLER_HOME/.aaxconfig.xml"
# GROUP=`stat -c %G $INSTALLER_HOME`
fi

if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
  # Source debconf library.
  . /usr/share/debconf/confmodule
  # Remove my changes to the db.
  db_purge

  # remove stale configuration files
  if [ $USER = "root" ]; then
    if [ -d /etc/aax ] ;then
      rm -f /etc/aax/config.xml > /dev/null;
      rmdir /etc/aax > /dev/null;
    fi
  fi
  rm -f $CONFIGFILE;
fi

if [ "$1" = "remove" ]; then
  ldconfig
fi
